api/urls.py
from django.urls import path

from rest_framework import routers

from .viewsets import ElementReadOnlyViewSet, ElementCreateUpdateDestroyViewSet,  CategoryViewSet, TypeViewSet, CommentViewSet, TodoViewSet
from . import views

route = routers.SimpleRouter()

route.register('element-lecture',ElementReadOnlyViewSet, basename='element-lecture')
route.register('element-write',ElementCreateUpdateDestroyViewSet, basename='element-write')
route.register('category',CategoryViewSet)
route.register('type',TypeViewSet)
route.register('comment',CommentViewSet)
route.register('todo',TodoViewSet)

urlpatterns = route.urls

urlpatterns += path('login', views.login),

elements/urls.py
from django.urls import path

from .views import add, index, update, delete, blog_list, blog_detail

app_name = 'elements'
urlpatterns = [
    path('', index, name='index'),
    path("add", add, name="add"),
    path('update/<int:pk>', update, name='update'),
    path('delete/<int:pk>', delete, name='delete'),
    path('blog/', blog_list, name='blog_list'),
    path('blog/<slug:slug>/', blog_detail, name='blog_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("comments.urls")),
    path('elements/', include("elements.urls")),  
    path('api/', include("api.urls")),  
    path('management/', include("management.urls")),  
    path('todo/', include("todo.urls")),  
    # auth
    path('', include("user.urls")),  
    path('', include("account.urls")),  
    path('pruebas/', include("pruebas.urls")),  
]+ debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elements/models.py
from django.core.exceptions import ValidationError

from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,blank=True)
    
    def __str__(self):
        return self.title
    
class Type(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,blank=True)
    
    def __str__(self):
        return self.title

class ElementManager(models.Manager):
    def get_queryset(self):
        # Siempre que usemos Element.objects.all(), incluirá el select_related
        return super().get_queryset().select_related('category', 'type')
    
class Element(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,blank=True)
    description = models.TextField() # blank=True, null=True
    price = models.DecimalField(max_digits=10,decimal_places=2, default=6.10) # 12345678.10
    category = models.ForeignKey(Category, on_delete=models.CASCADE) #, related_name='elements'
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    
    # Asignamos el manager personalizado
    # objects = ElementManager()
    
    # Realizar validaciones desde el modelo y se aplican en los formularios
    # def clean(self):
    #     if self.price < 0:
    #         raise ValidationError('Price cannot be negative')
    
    def __str__(self):
        return self.title

elements/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.utils.text import slugify

from .models import Element, Type, Category

class ElementForm(forms.Form):
    # title = forms.CharField(label="Título", max_length=255, min_length=3, validators=[MinLengthValidator(5, message='Very short! (min %(limit_value)d) current %(show_value)d ')])
    title = forms.CharField(label="Título", max_length=255, min_length=3, 
                            validators=[
                                MinLengthValidator(5,)
                                ])
    description = forms.CharField(label='Descripción', initial='Tu increible post por aquí', widget=forms.Textarea, validators=[MinLengthValidator(2, message='Very short! (min %(limit_value)d) current %(show_value)d ')])

    slug = forms.SlugField(label='Slug', max_length=255, widget=forms.TextInput(
        attrs = {
            'id': '50',
            'class': 'form-control'
        }
    ))
    # description = forms.CharField(widget=forms.Textarea, initial='Content Initial')
    price = forms.DecimalField(label='Price', decimal_places=2, max_digits=5, required=False)

    type = forms.ModelChoiceField(queryset=Type.objects.all(), initial=1)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), initial=1)

    # def clean_title(self):
    #     title = self.cleaned_data['title']
    #     if Element.objects.filter(title=title).exists():
    #         raise ValidationError("Title already exists")
    #     return title
    
    # def clean(self):
    #     form_data = self.cleaned_data
    #     if form_data["slug"] != slugify(form_data["title"]):
    #         self._errors["slug"] = ["Slug do not match with title"]
    #     return form_data


class ElemementModelForm(forms.ModelForm):
    class Meta:
        model = Element
        fields = '__all__'

elements/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import ElementForm # ,ElemementModelForm
from .models import Element, Category, Type

# Create your views here.

def add(request):
    if request.method == "POST":
        form = ElementForm(request.POST)
        if form.is_valid():
            element = Element()
            element.title = form.cleaned_data['title']
            element.slug = form.cleaned_data['slug']
            element.description = form.cleaned_data['description']
            element.price = form.cleaned_data['price']
            element.type = form.cleaned_data['type']
            element.category = form.cleaned_data['category']
            element.save()
    else:
        form = ElementForm()

    return render(request, 'elements/add.html', {'form':form})

def index(request):
    
    # categoria ejemplo
    # categorias = Category.objects.prefetch_related('elements').all()
    # for cat in categorias:
    #     print(f"Categoría: {cat.title}")
    #     # Aquí Django hace una consulta a la DB por CADA categoría para buscar sus elementos
    #     for el in cat.element_set.all(): 
    #         print(f" - Elemento: {el.title}")
    # categoria ejemplo
    
    elements = Element.objects.all()
    # elements = Element.objects.select_related('category', 'type').all()
    paginator = Paginator(elements, 15)
    page_number = request.GET.get('page')
    elements_page = paginator.get_page(page_number)
    return render(request,'elements/index.html',{'elements':elements_page})


def update(request, pk):
    
    element = get_object_or_404(Element, pk=pk)

    if request.method == "POST":
        form = ElementForm(request.POST)
        if form.is_valid():
            element.title = form.cleaned_data['title']
            element.slug = form.cleaned_data['slug']
            element.description = form.cleaned_data['description']
            element.price = form.cleaned_data['price']
            element.type = form.cleaned_data['type']
            element.category = form.cleaned_data['category']
            element.save()
    else:
         form = ElementForm(initial={
            'title': element.title, 
            'slug': element.slug, 
            'description': element.description,
            'price': element.price, 
            'type': element.type, 
            'category': element.category
        })

    return render(request,'elements/add.html',{'form':form, 'element': element})
    
def delete(request,pk):
    element = Element.objects.get(pk=pk)
    element.delete()
    return redirect('elements:index')

def blog_list(request):
    elements = Element.objects.all().order_by('-created')
    
    # Filters
    type_slug = request.GET.get('type')
    category_slug = request.GET.get('category')

    if type_slug:
        elements = elements.filter(type__slug=type_slug)
    
    if category_slug:
        elements = elements.filter(category__slug=category_slug)

    # Pagination
    paginator = Paginator(elements, 6) # 6 elements per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    types = Type.objects.all()
    categories = Category.objects.all()

    return render(request, 'elements/blog_list.html', {
        'page_obj': page_obj,
        'types': types,
        'categories': categories,
        'selected_type': type_slug,
        'selected_category': category_slug
    })

def blog_detail(request, slug):
    element = get_object_or_404(Element, slug=slug)
    return render(request, 'elements/blog_detail.html', {'element': element})

elements/templates/elements/add.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            <strong>{{ field.name }}:</strong>
            {{ error }}
          </div>
        {% endfor %}
      {% endfor %}
    {% endif %}
    
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Send</button>
    </form>
{% endblock content %}

elements/templates/elements/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Header -->
<header class="masthead"
    style="background-image: url('https://startbootstrap.github.io/startbootstrap-clean-blog/assets/img/post-bg.jpg'); background-size: cover; background-position: center; padding: 150px 0 100px; margin-bottom: 50px;">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading text-center text-white">
                    <h1 style="font-size: 55px;">{{ element.title }}</h1>
                    <h2 class="subheading" style="font-size: 26px; font-weight: 300; margin: 10px 0 30px;">{{
                        element.description|truncatewords:10 }}</h2>
                    <span class="meta fst-italic">
                        Posted by
                        <a href="#!" class="text-white">Start Bootstrap</a>
                        on {{ element.created|date:"F d, Y" }}
                    </span>
                    <div class="mt-3">
                        <span class="badge bg-light text-dark me-1">{{ element.category.title }}</span>
                        <span class="badge bg-secondary">{{ element.type.title }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content -->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="fs-5 mb-4">
                    {{ element.description|linebreaks }}
                </div>
                {% if element.price %}
                <p class="fw-bold fs-4">Price: ${{ element.price }}</p>
                {% endif %}

                <div class="mt-5">
                    <a href="{% url 'elements:blog_list' %}" class="btn btn-outline-secondary">&larr; Back to Blog</a>
                </div>
            </div>
        </div>
    </div>
</article>
{% endblock %}

elements/templates/elements/blog_list.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Header -->
<header class="masthead"
    style="background-image: url('https://startbootstrap.github.io/startbootstrap-clean-blog/assets/img/home-bg.jpg'); background-size: cover; background-position: center; padding: 150px 0 100px; margin-bottom: 50px;">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading text-center text-white">
                    <h1 style="font-size: 80px;">Clean Blog</h1>
                    <span class="subheading" style="font-size: 24px; font-weight: 300;">A Blog Theme by Start
                        Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <!-- Filters -->
            <div class="mb-5 text-center">
                <span class="text-muted me-2"><i class="fas fa-filter"></i> Filters:</span>
                {% for type in types %}
                <a href="?type={{ type.slug }}"
                    class="badge rounded-pill bg-light text-dark text-decoration-none border {% if selected_type == type.slug %}bg-secondary text-white{% endif %}">
                    {{ type.title }}</a>
                {% endfor %}
                {% for cat in categories %}
                <a href="?category={{ cat.slug }}"
                    class="badge rounded-pill bg-light text-dark text-decoration-none border {% if selected_category == cat.slug %}bg-secondary text-white{% endif %}">
                    {{ cat.title }}</a>
                {% endfor %}
                {% if selected_type or selected_category %}
                <a href="{% url 'elements:blog_list' %}" class="btn btn-link btn-sm text-muted"><i
                        class="fas fa-times"></i> Clear</a>
                {% endif %}
            </div>

            {% for element in page_obj %}
            <div class="post-preview">
                <a href="{% url 'elements:blog_detail' element.slug %}" class="text-decoration-none text-dark">
                    <h2 class="post-title" style="font-size: 36px; margin-top: 30px; margin-bottom: 10px;">
                        {{ element.title }}
                    </h2>
                    <h3 class="post-subtitle fw-light" style="font-weight: 300; margin: 0 0 10px;">
                        {{ element.description|truncatewords:20 }}
                    </h3>
                </a>
                <p class="post-meta text-muted fst-italic">
                    Posted by
                    <a href="#!" class="text-decoration-none">Start Bootstrap</a>
                    on {{ element.created|date:"F d, Y" }}
                    <span class="mx-2">&middot;</span>
                    <span class="badge bg-secondary">{{ element.category.title }}</span>
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% empty %}
            <p class="text-center text-muted">No posts found.</p>
            {% endfor %}

            <!-- Pagination -->
            {% if page_obj.has_other_pages %}
            <div class="d-flex justify-content-end mb-4">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase"
                    href="?page={{ page_obj.previous_page_number }}{% if selected_type %}&type={{ selected_type }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">&larr;
                    Newer Posts</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase ms-3"
                    href="?page={{ page_obj.next_page_number }}{% if selected_type %}&type={{ selected_type }}{% endif %}{% if selected_category %}&category={{ selected_category }}{% endif %}">Older
                    Posts &rarr;</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

elements/templates/elements/index.html
{% extends "base.html" %}



{% block head %}

    <title>Elmement List</title>

{% endblock %}



{% block content %}

    <div class="container">

        <a href="{% url 'elements:add' %}" class="add-link">Add Element</a>

        {% for e in elements %}

            <div class="comment-card">

                <p>{{ e.id }} - {{ e.title }} - {{ e.category.title }}</p>

                <p class="date">{{ e.created }}</p>

                <div class="comment-actions">

                    <a href="{% url 'elements:update' e.id %}" class="btn btn-edit">Edit</a>

                    <form action="{% url 'elements:delete' e.id %}" method="post">

                        {% csrf_token %}

                        <button type="submit" class="btn btn-delete">Delete</button>

                    </form>

                </div>

            </div>

        {% endfor %}

        <!-- Paginación -->
    {% include 'partials/pagination.html' with page_obj=elements %}

    </div>

{% endblock %}
 la comparación:
</p>
<pre><code class="language-plaintext">if (person.getName().toLowerCase().contains(filterPattern))
</code></pre>
<p>
    En nuestro caso nos interesa que NO sea sensible a mayúsculas/minúsculas y que contenga (<code>contains</code>) la palabra o sección clave y de esta forma tener un filtro bastante flexible, pero puedes expresarlo como desees.
</p>
<p>
    <a target="_blank" rel="noopener noreferrer" href="https://github.com/libredesarrollo/android-studio/tree/master/RecyclerViewFilter">Descargar</a>
</p>